# Generated by Django 4.2.28 on 2026-05-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NgsSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=255)),
                ('final_concentration', models.FloatField(blank=True, null=True)),
                ('bioanalyzer_file', models.FileField(blank=True, null=True, upload_to='ngs_samples/bioanalyzer/')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='api.fastq')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('sample_type', models.CharField(blank=True, choices=[('cell_line', 'Cell Line'), ('primary_culture', 'Primary Culture'), ('tissue', 'Tissue'), ('organoid', 'Organoid'), ('other', 'Other')], max_length=50)),
                ('plasmid_number', models.IntegerField(blank=True, null=True)),
                ('production_number', models.IntegerField(blank=True, null=True)),
                ('biological_model', models.CharField(blank=True, max_length=255)),
                ('organ', models.CharField(blank=True, max_length=255)),
                ('serotype', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file', models.FileField(blank=True, null=True, upload_to='pipelines/scripts/')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngs_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_batches', to='api.ngssample')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_json', models.FileField(blank=True, null=True, upload_to='pipelines/settings/')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.script')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50)),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='sequencing_products/summaries/')),
                ('sequencing_machine', models.CharField(blank=True, max_length=255)),
                ('flowcell', models.CharField(blank=True, max_length=255)),
                ('read_length', models.IntegerField(blank=True, null=True)),
                ('read_depth', models.IntegerField(blank=True, null=True)),
                ('phix_proportion', models.FloatField(blank=True, null=True)),
                ('custom_recipe', models.BooleanField(default=False)),
                ('custom_recipe_start', models.IntegerField(blank=True, null=True)),
                ('custom_recipe_end', models.IntegerField(blank=True, null=True)),
                ('sequencing_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_products', to='api.sequencingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='sequencing_batches/files/')),
                ('table_de_calcul', models.FileField(blank=True, null=True, upload_to='sequencing_batches/tables/')),
                ('sequencing_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_files', to='api.sequencingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primer_pair', models.CharField(blank=True, max_length=255)),
                ('commentary', models.CharField(blank=True, max_length=1000)),
                ('protocol_description_file', models.FileField(blank=True, null=True, upload_to='protocols/descriptions/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='api.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ngssample',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngs_samples', to='api.protocol'),
        ),
        migrations.CreateModel(
            name='FastqFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='fastq/files/')),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastq_files', to='api.fastq')),
            ],
        ),
        migrations.AddField(
            model_name='fastq',
            name='sequencing_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastqs', to='api.sequencingproduct'),
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_file', models.FileField(blank=True, null=True, upload_to='pipelines/counts/')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='api.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimming_table_file', models.FileField(blank=True, null=True, upload_to='pipelines/analysis/trimming/')),
                ('logo_plot_file', models.FileField(blank=True, null=True, upload_to='pipelines/analysis/logo/')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.pipeline')),
            ],
        ),
    ]
