# Generated by Django 4.2.28 on 2026-09-16 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='api.fastq')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution de pipeline',
                'verbose_name_plural': 'Exécutions de pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('bash', 'Bash'), ('other', 'Autre')], default='python', max_length=20)),
                ('docker_image', models.CharField(default='python:3.11-slim', help_text="Image Docker exécutant l'étape (ex : python:3.11-slim, gcc:13, debian:bookworm-slim).", max_length=255)),
                ('script_file', models.FileField(blank=True, help_text="Code source de l'étape, monté dans le conteneur sous /work/script.<ext>.", null=True, upload_to='pipeline_templates/scripts/')),
                ('command', models.TextField(help_text='Commande shell exécutée dans le conteneur (cwd=/work). Entrées disponibles dans /work/in/, sorties attendues dans /work/out/. Ex : python /work/script.py --input /work/in --output /work/out')),
                ('timeout_seconds', models.IntegerField(blank=True, help_text="Délai maximal d'exécution avant échec forcé (par défaut : valeur globale du projet).", null=True)),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Étapes du même modèle qui doivent réussir avant celle-ci.', related_name='dependents', to='api.pipelinestep')),
            ],
            options={
                'verbose_name': 'Étape de pipeline',
                'verbose_name_plural': 'Étapes de pipeline',
                'ordering': ['template', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de pipeline',
                'verbose_name_plural': 'Modèles de pipeline',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.CreateModel(
            name='StepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('queued', 'En file'), ('running', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué'), ('skipped', 'Ignorée')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='api.pipelinerun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.pipelinestep')),
            ],
            options={
                'verbose_name': "Exécution d'étape",
                'verbose_name_plural': "Exécutions d'étape",
                'ordering': ['pipeline_run', 'step__name'],
                'unique_together': {('pipeline_run', 'step')},
            },
        ),
        migrations.CreateModel(
            name='StepArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('input', 'Entrée'), ('output', 'Sortie')], max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pipeline_runs/artifacts/%Y/%m/%d/')),
                ('step_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.steprun')),
            ],
            options={
                'verbose_name': 'Fichier de pipeline',
                'verbose_name_plural': 'Fichiers de pipeline',
                'ordering': ['step_run', 'kind', 'label'],
            },
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.pipelinetemplate'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.pipelinetemplate'),
        ),
    ]
