# Generated by Django 4.2.28 on 2026-09-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pipelinerun_pipelinestep_pipelinetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_runs', to='api.fastq')),
            ],
            options={
                'verbose_name': 'Suivi manuel',
                'verbose_name_plural': 'Suivis manuels',
            },
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='count',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='script',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.AddField(
            model_name='analysis',
            name='manual_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.manualrun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='manual_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='api.manualrun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='manual_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.manualrun'),
            preserve_default=False,
        ),
    ]
