# Generated by Django 4.2.28 on 2026-09-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_manualrun_remove_analysis_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='script_file',
        ),
        migrations.AddField(
            model_name='fastqfile',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='script',
            field=models.ForeignKey(blank=True, help_text='Script du registre à exécuter (monté dans le conteneur sous /work/script.<ext>).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='api.script'),
        ),
        migrations.AddField(
            model_name='script',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('bash', 'Bash'), ('other', 'Autre')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='script',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='script',
            name='manual_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.manualrun'),
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('total_size', models.BigIntegerField()),
                ('offset', models.BigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to='api.fastq')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envoi de fichier (par morceaux)',
                'verbose_name_plural': 'Envois de fichiers (par morceaux)',
                'ordering': ['-created_at'],
            },
        ),
    ]
