# Generated by Django 4.2.28 on 2026-09-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cleanup_stale_uploads_periodic_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunkedupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chunked upload', 'verbose_name_plural': 'Chunked uploads'},
        ),
        migrations.AlterModelOptions(
            name='manualrun',
            options={'verbose_name': 'Manual run', 'verbose_name_plural': 'Manual runs'},
        ),
        migrations.AlterModelOptions(
            name='pipelinerun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pipeline run', 'verbose_name_plural': 'Pipeline runs'},
        ),
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'ordering': ['template', 'name'], 'verbose_name': 'Pipeline step', 'verbose_name_plural': 'Pipeline steps'},
        ),
        migrations.AlterModelOptions(
            name='pipelinetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Pipeline template', 'verbose_name_plural': 'Pipeline templates'},
        ),
        migrations.AlterModelOptions(
            name='stepartifact',
            options={'ordering': ['step_run', 'kind', 'label'], 'verbose_name': 'Pipeline file', 'verbose_name_plural': 'Pipeline files'},
        ),
        migrations.AlterModelOptions(
            name='steprun',
            options={'ordering': ['pipeline_run', 'step__name'], 'verbose_name': 'Step run', 'verbose_name_plural': 'Step runs'},
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='command',
            field=models.TextField(help_text='Shell command executed in the container (cwd=/work). Inputs are available in /work/in/, outputs are expected in /work/out/. E.g.: python /work/script.py --input /work/in --output /work/out'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Steps in the same template that must succeed before this one.', related_name='dependents', to='api.pipelinestep'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='docker_image',
            field=models.CharField(default='python:3.11-slim', help_text='Docker image that runs the step (e.g. python:3.11-slim, gcc:13, debian:bookworm-slim).', max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('bash', 'Bash'), ('other', 'Other')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='script',
            field=models.ForeignKey(blank=True, help_text='Registry script to run (mounted in the container as /work/script.<ext>).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='api.script'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='timeout_seconds',
            field=models.IntegerField(blank=True, help_text='Maximum execution time before forced failure (defaults to the project-wide value).', null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('bash', 'Bash'), ('other', 'Other')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencingbatchfile',
            name='table_de_calcul',
            field=models.FileField(blank=True, null=True, upload_to='sequencing_batches/tables/', verbose_name='calculation table'),
        ),
        migrations.AlterField(
            model_name='stepartifact',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10),
        ),
        migrations.AlterField(
            model_name='steprun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
