# Generated by Django 4.2.28 on 2026-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_cleanup_periodic_task_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='injection_type',
            field=models.CharField(blank=True, choices=[('sub_retinal', 'Sub retinal'), ('intra_vitreal', 'Intra vitreal'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='injection_type_other',
            field=models.CharField(blank=True, help_text='Shown only when Injection type = Other.', max_length=255, verbose_name='Injection type (other)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='organ_other',
            field=models.CharField(blank=True, help_text='Shown only when Organ = Other.', max_length=255, verbose_name='Organ (other)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type_other',
            field=models.CharField(blank=True, help_text='Shown only when Sample type = Other.', max_length=255, verbose_name='Sample type (other)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='serotype_other',
            field=models.CharField(blank=True, help_text='Shown only when Serotype = Other.', max_length=255, verbose_name='Serotype (other)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='biological_model',
            field=models.CharField(blank=True, choices=[('human', 'Human'), ('macaca_mulatta', 'Macaca mulata'), ('chlorocebus', 'Chlorocebeus'), ('mouse', 'Mouse'), ('pig', 'Pig'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='condition',
            field=models.CharField(blank=True, choices=[('ex_vivo', 'Ex vivo'), ('in_vivo', 'In vivo'), ('in_vitro', 'In vitro')], max_length=50, verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organ',
            field=models.CharField(blank=True, choices=[('retina', 'Retina'), ('brain_cortex', 'Brain-Cortex'), ('brain_lgn', 'Brain-LGN'), ('muscle', 'Muscle'), ('cochlea', 'Cochlea'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='plasmid_number',
            field=models.IntegerField(blank=True, help_text='Shown only when Sample type = Plasmid.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='production_number',
            field=models.IntegerField(blank=True, help_text='Shown only when Sample type = AAV.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('cell_line', 'Cell Line'), ('primary_culture', 'Primary Culture'), ('tissue', 'Tissue'), ('organoid', 'Organoid'), ('aav', 'AAV'), ('plasmid', 'Plasmid'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='serotype',
            field=models.CharField(blank=True, choices=[('aav2', 'AAV2'), ('aav5', 'AAV5'), ('aav9', 'AAV9'), ('other', 'Other')], max_length=50),
        ),
    ]
