# Generated by Django 4.2.28 on 2026-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sample_injection_type_sample_injection_type_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='sample',
        ),
        migrations.AddField(
            model_name='protocol',
            name='samples',
            field=models.ManyToManyField(help_text='One protocol can be associated with several samples.', related_name='protocols', to='api.sample'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='commentary',
            field=models.TextField(blank=True),
        ),
    ]
