# Generated by Django 4.2.28 on 2026-09-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_protocol_sample_protocol_samples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngssample',
            name='index',
        ),
        migrations.AddField(
            model_name='ngssample',
            name='index_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Index 1'),
        ),
        migrations.AddField(
            model_name='ngssample',
            name='index_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Index 2'),
        ),
        migrations.AddField(
            model_name='ngssample',
            name='operating_name',
            field=models.CharField(default='', help_text="Sequencing operating name. Defaults to the originating sample's name.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngssample',
            name='sample',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ngs_sample', to='api.sample'),
            preserve_default=False,
        ),
    ]
