# Generated by Django 4.2.28 on 2026-09-29 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ngssample_index_ngssample_index_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencingbatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='manualrun',
            name='fastq',
        ),
        migrations.RemoveField(
            model_name='sequencingbatch',
            name='ngs_sample',
        ),
        migrations.AddField(
            model_name='fastq',
            name='ngs_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastqs', to='api.ngssample'),
        ),
        migrations.AddField(
            model_name='manualrun',
            name='sequencing_product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manual_run', to='api.sequencingproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngssample',
            name='sequencing_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngs_samples', to='api.sequencingbatch'),
        ),
        migrations.AddField(
            model_name='sequencingbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScriptParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.script')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
