# Generated by Django 4.2.28 on 2026-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sequencingbatch_options_remove_manualrun_fastq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='command',
            field=models.TextField(help_text="Shell command executed in the container (cwd=/work). Inputs are available in /work/in/, outputs are expected in /work/out/. E.g.: python /work/script.py --input /work/in --output /work/out. If the script writes a report.json file to /work/out/, it is captured as the step's execution report and its contents are shown on the run's report page."),
        ),
        migrations.AlterField(
            model_name='stepartifact',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('report', 'Report')], max_length=10),
        ),
    ]
