# Generated by Django 4.2.28 on 2026-09-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pipelinestep_command_alter_stepartifact_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='primer_pair',
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='primer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_as_primer_1', to='api.primer'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='primer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_as_primer_2', to='api.primer'),
        ),
    ]
