# Generated by Django 4.2.28 on 2026-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_primer_remove_protocol_primer_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
