# Generated by Django 4.2.28 on 2026-09-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_protocol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='report_filename',
            field=models.CharField(blank=True, default='report.json', help_text="Name of the JSON execution-report file this script writes to /work/out/ (used to identify and display it on the pipeline run's report page).", max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='command',
            field=models.TextField(help_text="Shell command executed in the container (cwd=/work). Inputs are available in /work/in/, outputs are expected in /work/out/. E.g.: python /work/script.py --input /work/in --output /work/out. If the script writes its report JSON file (name set on the Script itself, default report.json) to /work/out/, it is captured as the step's execution report and its contents are shown on the run's report page."),
        ),
    ]
