# Generated by Django 4.2.28 on 2026-02-23 12:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_human', models.BooleanField(blank=True, default=True, help_text='Designates whether this is a human user account (vs team/service/technical account)', null=True, verbose_name='human account')),
                ('is_director', models.BooleanField(default=False, help_text='Designates whether the user is a director who can validate all access requests', verbose_name='director status')),
                ('ldap_created_date', models.DateTimeField(blank=True, help_text='When the account was created in Active Directory', null=True, verbose_name='LDAP creation date')),
                ('ldap_modified_date', models.DateTimeField(blank=True, help_text='Last time the account was modified in Active Directory', null=True, verbose_name='LDAP modification date')),
                ('ldap_last_logon', models.DateTimeField(blank=True, help_text='Last logon time from Active Directory', null=True, verbose_name='LDAP last logon')),
                ('ldap_password_last_set', models.DateTimeField(blank=True, help_text='When the password was last changed in Active Directory', null=True, verbose_name='LDAP password last set')),
                ('ldap_account_expires', models.DateTimeField(blank=True, help_text='Account expiration date from Active Directory', null=True, verbose_name='LDAP account expiration')),
                ('ldap_last_sync', models.DateTimeField(blank=True, help_text='Last time this user was synchronized with LDAP', null=True, verbose_name='Last LDAP sync')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=100, unique=True, verbose_name='category name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the LDAP/AD group (CN value)', max_length=255, unique=True, verbose_name='group name')),
                ('distinguished_name', models.TextField(help_text='Full DN of the group in LDAP', unique=True, verbose_name='distinguished name')),
                ('description', models.TextField(blank=True, help_text='Description of the group', verbose_name='description')),
                ('human_name', models.CharField(default='Unknown', max_length=50, verbose_name='human name')),
                ('group_type', models.CharField(choices=[('HUMAN', 'human'), ('MACHINE', 'machine'), ('MIXED', 'mixed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', verbose_name='Group is human')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Users who can validate access requests for this group', related_name='managed_ldap_groups', to=settings.AUTH_USER_MODEL, verbose_name='Group managers')),
            ],
            options={
                'verbose_name': 'LDAP Group',
                'verbose_name_plural': 'LDAP Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user_set', to='authentication.customusercategory', verbose_name='User category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ldap_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='authentication.ldapgroup', verbose_name='LDAP groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
